version = 3
final_space = true

[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  os = '#F47828'
  pink = '#F5C2E7'
  violet = '#CBA6F7'
  aqua = '#94E2D5'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    template = '{{.Icon}} '
    foreground = 'p:os'
    style = 'plain'

  [[blocks.segments]]
    type = 'session'
    template = '{{ .UserName }}@{{ .HostName }} '
    foreground = 'p:blue'
    style = 'plain'

  [[blocks.segments]]
        type = 'executiontime'
        template = ' {{ .FormattedMs }} '
        foreground = 'p:violet'
        style = 'plain'
    
        [blocks.segments.properties]
          threshold = 500
          style = 'austin'
          always_enabled = true

  [[blocks.segments]]
    type = 'path'
    template = ' {{ .Path }} '
    foreground = 'p:aqua'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    template = '{{ .HEAD }} '
    foreground = 'p:lavender'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    template = ''
    foreground = 'p:closer'
    style = 'plain'

[transient_prompt]
  template = '> '
  foreground = 'p:os'
  background = 'transparent'
